# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    serializer:
        enabled: true

    session:
        enabled: false

when@test:
    framework:
        test: true
        session:
            enabled: false